		<div id="menu">
			<ul>
				<li class="tit">Gastos</li>
				<li><a href="<?php echo $this->baseUrl ?>/conceptos/admin">Conceptos</a></li>
				<li><a href="<?php echo $this->baseUrl ?>/tipos_gastos/admin">Tipo de gastos</a></li>
				<li><a href="<?php echo $this->baseUrl ?>/gastos/admin">Gastos</a></li>
			</ul>
				<br />
				<hr size="1" />
				<br />
			<ul>
				<li class="tit">Noticias</li>
				<li><a href="<?php echo $this->baseUrl ?>/noticias/admin">Noticias</a></li>
			</ul>
				<br />
				<hr size="1" />
				<br />
			<ul>
				<li class="tit">Parametrizacion</li>
				<li><a href="<?php echo $this->baseUrl ?>/secciones/admin">Secciones</a></li>
				<li><a href="<?php echo $this->baseUrl ?>/autores/admin">Autores</a></li>
			</ul>
				<br />
				<hr size="1" />
				<br />
			<ul>
				<li class="tit"><a href="<?php echo $this->baseUrl ?>/autenticacion/admin/logout">Salir</a></li>
			</ul>
		</div>