<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
<?php echo $this->headMeta()->appendHttpEquiv(
	'Content-Type',
	'text/html; Charset=UTF-8'
); ?>
<?php echo $this->headTitle(); ?>

<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/html/styles/site.css" />

<?php echo $this->render('_scripts.phtml'); ?>
</head>
<body>
	<div id="header">
		<img alt="logo" src="<?php echo $this->baseUrl;?>/html/images/logo.jpg" border="0" />
	</div>