<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<head>
<?php echo $this->headMeta()->appendHttpEquiv(
	'Content-Type',
	'text/html; Charset=UTF-8'
); ?>
<?php echo $this->headTitle(); ?>

<link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/html/styles/site.css" />
<script src="<?php echo $this->baseUrl;?>/html/clientScripts/site.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/html/clientScripts/mootools/mootools.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/html/clientScripts/mootools/fvalidator.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/html/clientScripts/mootools/calendar.js" type="text/javascript"></script>
</head>
<body>
	<div id="header">
		<img alt="logo" src="<?php echo $this->baseUrl;?>/html/images/logo.jpg" border="0" />
	</div>